import colorPalette from '../colorPalette';
import { GlobalTheme } from '../globalTheme/globalTheme';

export const darkTheme: GlobalTheme = {
  palette: {
    background: {
      '100': '#3a3a4a',
      '200': '#26262e',
      '300': '#1b1a1f',
    },
  },
  color: {
    toggle: {
      primary: colorPalette.primary['500'],
      secondary: colorPalette.secondary['500'],
      get: colorPalette.get['500'],
      post: colorPalette.post['500'],
      put: colorPalette.put['500'],
      patch: colorPalette.patch['500'],
      delete: colorPalette.delete['500'],
      grey: colorPalette.grey['500'],
    },
    typography: {
      primary: colorPalette.primary['500'],
      secondary: colorPalette.secondary['500'],
      get: colorPalette.get['500'],
      post: colorPalette.post['500'],
      put: colorPalette.put['500'],
      patch: colorPalette.patch['500'],
      delete: colorPalette.delete['500'],
      grey: colorPalette.grey['500'],
      danger: colorPalette.original.red,
      warning: colorPalette.original.yellow,
      light: colorPalette.original.light,
      dark: colorPalette.original.dark,
    },
    icon: {
      primary: colorPalette.primary['500'],
      secondary: colorPalette.secondary['500'],
      get: colorPalette.get['500'],
      post: colorPalette.post['500'],
      put: colorPalette.put['500'],
      patch: colorPalette.patch['500'],
      delete: colorPalette.delete['500'],
      grey: colorPalette.grey['500'],
      danger: colorPalette.original.red,
      warning: colorPalette.original.yellow,
      light: colorPalette.original.light,
      dark: colorPalette.original.dark,
    },
    button: {
      contained: {
        primary: {
          main: colorPalette.primary['400'],
          hover: colorPalette.primary['500'],
          active: colorPalette.primary['400'],
          disabled: colorPalette.grey['700'],
        },
        secondary: {
          main: colorPalette.secondary['400'],
          hover: colorPalette.secondary['500'],
          active: colorPalette.secondary['400'],
          disabled: colorPalette.grey['700'],
        },
        get: {
          main: colorPalette.get['400'],
          hover: colorPalette.get['500'],
          active: colorPalette.get['400'],
          disabled: colorPalette.grey['700'],
        },
        post: {
          main: colorPalette.post['400'],
          hover: colorPalette.post['500'],
          active: colorPalette.post['400'],
          disabled: colorPalette.grey['700'],
        },
        put: {
          main: colorPalette.put['400'],
          hover: colorPalette.put['500'],
          active: colorPalette.put['400'],
          disabled: colorPalette.grey['700'],
        },
        patch: {
          main: colorPalette.patch['400'],
          hover: colorPalette.patch['500'],
          active: colorPalette.patch['400'],
          disabled: colorPalette.grey['700'],
        },
        delete: {
          main: colorPalette.delete['400'],
          hover: colorPalette.delete['500'],
          active: colorPalette.delete['400'],
          disabled: colorPalette.grey['700'],
        },
        grey: {
          main: colorPalette.grey['500'],
          hover: colorPalette.grey['400'],
          active: colorPalette.grey['500'],
          disabled: colorPalette.grey['700'],
        },
      },
      outlined: {
        primary: {
          main: colorPalette.primary['100'],
          hover: colorPalette.primary['50'],
          active: colorPalette.primary['50'],
          disabled: colorPalette.grey['600'],
        },
        secondary: {
          main: colorPalette.secondary['100'],
          hover: colorPalette.secondary['50'],
          active: colorPalette.secondary['50'],
          disabled: colorPalette.grey['600'],
        },
        get: {
          main: colorPalette.get['300'],
          hover: colorPalette.get['50'],
          active: colorPalette.get['50'],
          disabled: colorPalette.grey['600'],
        },
        post: {
          main: colorPalette.post['400'],
          hover: colorPalette.post['50'],
          active: colorPalette.post['50'],
          disabled: colorPalette.grey['600'],
        },
        put: {
          main: colorPalette.put['400'],
          hover: colorPalette.put['50'],
          active: colorPalette.put['50'],
          disabled: colorPalette.grey['600'],
        },
        patch: {
          main: colorPalette.patch['100'],
          hover: colorPalette.patch['50'],
          active: colorPalette.patch['50'],
          disabled: colorPalette.grey['600'],
        },
        delete: {
          main: colorPalette.delete['400'],
          hover: colorPalette.delete['50'],
          active: colorPalette.delete['50'],
          disabled: colorPalette.grey['600'],
        },
        grey: {
          main: colorPalette.grey['400'],
          hover: colorPalette.grey['50'],
          active: colorPalette.grey['50'],
          disabled: colorPalette.grey['600'],
        },
      },
    },
  },
  size: {
    typography: {
      '3xs': 0.5,
      '2xs': 0.625,
      xs: 0.75,
      sm: 0.875,
      md: 1,
      lg: 1.125,
      xl: 1.25,
      '2xl': 1.375,
      '3xl': 1.5,
    },
    icon: {
      '3xs': 0.5,
      '2xs': 0.625,
      xs: 0.75,
      sm: 0.875,
      md: 1,
      lg: 1.125,
      xl: 1.25,
      '2xl': 1.375,
      '3xl': 1.5,
    },
    button: {
      small: 2,
      medium: 2.25,
      large: 2.5,
    },
  },
};
