name: 'Storybook Deploy'

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # stage : checkout
      - name: Stage 1. checkout code
        uses: actions/checkout@v3

      # stage : ssh
      - name: Stage 2. ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # 기존 storybook 중단
            pm2 stop storybook
            pm2 delete storybook

            # 프로젝트 디렉토리 이동
            cd ./Develop/shooot-fe

            # main 브랜치 최신화
            git pull origin main

            # 패키지 업데이트
            npm install

            # 스토리북 실행
            pm2 start npm --name "storybook" -- run storybook
